### ISSUE TITLE
HomeAssistant integration

### ISSUE THREAD

**Issue by pergolafabio** [tobadia/petGPS#13]
Bought myself too a CAT gps Tracker, its indeed also based on 365GPS (topin)
http://www.topin.hk/web/

![image](https://user-images.githubusercontent.com/43251136/138118014-7a7074e7-53cd-4e54-934d-ac950de02f53.png)

is there also an integration possible for Home Assistant?

thnx in advance

**Comment by tobadia** [comment]
Ah well. Maybe they changed their firmware. For sure when I send "DOMAIN" to mine it answers with the current domain.
You can try "SERVER" as well.

In all my tests, it did revert to the default if my own server was not answering for a while, so I never really bother about "what if" :)

**Comment by tobadia** [comment]
Yeah it's a hole lot more. I gave it a try and it was a bit cumbersome to compile. Mostly based on java, and I'm not java-fluent. I did dig into their sources to get an idea of how they were parsing hex packets though. it did work. Just way more than I needed for my use case.

**Comment by pergolafabio** [comment]
:-)

probably an overkill, but again, verry easy for Home Assistant, they also have it availiable as docker add-on, so verry easy to install/maintain

**Comment by pergolafabio** [comment]
hey @tobadia , 1 more quick question... 
There is an SMS command to change the upload time interval... but is SMS on the only method to change stuff?? because i need to send SMS , and i also receive an SMS, when i want to set the time... this is a cost each time of 2 SMS

when i use the official 365GPS , i can just change settings there, without any additinal costs ...
always, if my pet is back, i change the time interval, otherwise, the battery is draining :-)

is there any other method to change this? i dont think the 365GPS is sending SMS messages, becase i dont see any transactions/costs then

also, do you know there is a command to turn the device on/off? also in gps365 , there is a remote on/off command

thnx, appreciated

**Comment by tobadia** [comment]
Hey,
I reckon there are a lot of possible packets to be sent to the device. I did not implement the "administration" part mostly because that would have required a UI around that Python server, to decide "what packet to send". And I'm not familier wityh Pytyon UI.
If you look at the docs (that are arguable poorly described) you can find that for packet type `0x97`:

> 0x97 server settings upload interval
> 
> Server sent to device
> Start bit 2byte Packet length 1byte Protocol number 1byte Upload interval 2byte Endbit 2byte
> Eg.7878 03 97 0050 0D0A
> The upload interval is set to 0050=80 seconds to upload once, and the upload interval is 10-7200 seconds.

So in theory, if the server sends `7878039700500D0A`, the device should change the upload interval to 80 seconds. I believe any administrative modification can be done through similar packets (see the Word document in the resources folder). However, one would need to think about how to "trigger" them manually. I can see a 2-window process, one with the server running (e.g. background discussion between device and server) and another windows, with the way of hijacking that "normal discussion" by sending a packet manually.

**Comment by pergolafabio** [comment]
ok, thnx for sharing

well, i always use the remote turn off/on feature, never press the button
but i also send the command for low interval upload, because when i send a remore off, but still time interval with 1 / 10 min, it still drains battery

when turned off, its possible to send a remote turn on again, i think its in somekind of sleep mode, all leds are off

**Comment by tobadia** [comment]
If you actually *never* press the button I'm going to guess it's in a low-power mode at all time. On mine (that is lost somewhere in a drawer) after a few minutes not moving, it would go to low-power, and wake-up should any movement be detected. However, turning it off by long-pressing the button would prevent that.

**Comment by pergolafabio** [comment]
hmm, dont think mine is going to a low-power mode , maybe its how the interval it setup
i need to activate sleep mode manually

thnx for feedback
